"""empty message

Revision ID: 35f871a91a88
Revises: a8048534b110
Create Date: 2022-02-16 20:22:04.356784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f871a91a88'
down_revision = 'a8048534b110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user', sa.String(length=225), nullable=False),
    sa.Column('ref_name', sa.UnicodeText(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('command_used', sa.UnicodeText(), nullable=False),
    sa.Column('syear', sa.Integer(), nullable=False),
    sa.Column('smonth', sa.Integer(), nullable=False),
    sa.Column('sday', sa.Integer(), nullable=False),
    sa.Column('stime', sa.Time(), nullable=False),
    sa.Column('completedOn', sa.DateTime(), nullable=True),
    sa.Column('tool_used', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
